pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint0: {trajectory: 0.1, goal: 0.1}
    joint1: {trajectory: 0.1, goal: 0.1}
    joint2: {trajectory: 0.1, goal: 0.1}
    joint3: {trajectory: 0.1, goal: 0.1}
    joint4: {trajectory: 0.1, goal: 0.1}
    joint5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 125

gripper_joint_position:
  type: position_controllers/JointTrajectoryController
  joints: &robot_joints
    - gripper_base_to_finger_right
    - gripper_base_to_finger_left
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_base_to_finger_right: {trajectory: 0.1, goal: 0.1}
    gripper_base_to_finger_right: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 125
    