gripper_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

gripper_joint_position:
  type: position_controllers/JointTrajectoryController
  joints: &robot_joints
  - gripper_base_to_finger_right
  - gripper_base_to_finger_left
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_base_to_finger_right: {trajectory: 0.1, goal: 0.1}
    gripper_base_to_finger_right: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 125
  action_monitor_rate: 10

gripper_joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints
    